### ISSUE TITLE
Design: UI revamp of complete app

### ISSUE THREAD

**Issue by SarveshChavan** [IEEE-VIT/hackfest-flutter#70]
### Description:
UI revamp of the app based on the designs in [figma file](https://www.figma.com/file/QP1vkEh0a7joS484npSShD/Git-Repo-Viewer?type=design&node-id=0%3A1&mode=design&t=IBWYg9jsP9hqBEDr-1).

### Sub Issues:
- [x] Create an app icon #82    -  @Yash-Waghmare 
- [x] Make app drawer #78   - @Lomesh21 
- [x] Adding new themes and Search Page UI updation #77  - @SarveshChavan 
- [x] Creating profile page #81  - @Lomesh21 
- [x] Contributors Page UI #88  - @Lomesh21 
- [x] Bookmark Page UI #89  - @Yash-Waghmare 
- [ ] About Us Page UI #92 - @Yash-Waghmare 

### Resource:
- [Material 3 Design](https://m3.material.io/) 
- [Flutter UI docs](https://docs.flutter.dev/ui) 

### Note:
I expect progress, so one assigned has to report every 3 days

**Comment by Lomesh21** [comment]
@dk-a-dev If you find these UI interesting then I am grateful to take it

**Comment by dk-a-dev** [comment]
@SarveshChavan sorry for replying late, im looking into the possibility for this plz be patient

**Comment by SarveshChavan** [comment]
pardon me, but I just raised an issue nothing else @Lomesh21 asked to work on it. leave it  aside, when you get time please check this Figma design and let me know your comments.
https://www.figma.com/file/QP1vkEh0a7joS484npSShD/Git-Repo-Viewer?type=design&node-id=0%3A1&mode=design&t=IBWYg9jsP9hqBEDr-1

**Comment by dk-a-dev** [comment]
@SarveshChavan i told u yesterday i will create an issue for design :) just wait let all imp feats get implemented and major bugs get resolved u both can work together on design part

**Comment by dk-a-dev** [comment]
More issues will be added by tomorrow

**Comment by dk-a-dev** [comment]
@SarveshChavan make that figma file any one can edit with link

**Comment by SarveshChavan** [comment]
I'll give you the edit access or do one thing create your own link I'll add those designs in that figma link of yours.

**Comment by dk-a-dev** [comment]
> I'll give you the edit access or do one thing create your own link I'll add those designs in that figma link of yours.

Just open the link for everyone by giving edit access I will not create a new one

**Comment by dk-a-dev** [comment]
@Lomesh21 I have assigned this issue to @SarveshChavan
the boy had done a great job with design refer [figma file](https://www.figma.com/file/QP1vkEh0a7joS484npSShD/Git-Repo-Viewer?type=design&node-id=0%3A1&mode=design&t=IBWYg9jsP9hqBEDr-1)
Let me know if you are interested in helping him out in this total revamp so I can also assign the issue to u and then work in collab with him
You guys can communicate using [IEEE-VIT Discord](https://discord.gg/E5dbJyyMc) and also keep me in loop

**Comment by Lomesh21** [comment]
@dk-a-dev Of course, I am ready to contribute instead of sitting idle

**Comment by Lomesh21** [comment]
@dk-a-dev I have gone through figma designs, Can I work on profile page first

**Comment by dk-a-dev** [comment]
@Lomesh21 communicate with @SarveshChavan divide work make use of our discord or share each other usernames, work in collab

**Comment by SarveshChavan** [comment]
I don't have any problem @Lomesh21 can take the Profile page and also if he is interested he can have the drawer widget

**Comment by Lomesh21** [comment]
@dk-a-dev Everything is awesome but creating a fork for working together?? I didn't get it means can't we work on same fork??

**Comment by Yash-Waghmare** [comment]
Hey @dk-a-dev 

> pardon me, but I just raised an issue nothing else @Lomesh21 asked to work on it. leave it aside, when you get time please check this Figma design and let me know your comments. https://www.figma.com/file/QP1vkEh0a7joS484npSShD/Git-Repo-Viewer?type=design&node-id=0%3A1&mode=design&t=IBWYg9jsP9hqBEDr-1

Hey @dk-a-dev, @SarveshChavan, I went through the design and am interested in collaboration, as there are too many pages, I can work on some screens or create an app icon for the application!

**Comment by dk-a-dev** [comment]
> Hey @dk-a-dev, @SarveshChavan, I went through the design and am interested in collaboration, as there are too many pages, I can work on some screens or create an app icon for the application!

yes sure u can work in collab with others....
app icon part is urs go ahead @Yash-Waghmare

**Comment by dk-a-dev** [comment]
@Lomesh21, @SarveshChavan and @Yash-Waghmare 
this is wht my senior said:
"We can’t make the branch in our repo, they will have to talk with themselves and create one in one of their forks and work in collab there"
So no possibility I can create a "master-ui" branch here u guys can work on a branch forking and collab a/c

**Comment by Yash-Waghmare** [comment]
> Collaborator

Sure

**Comment by Lomesh21** [comment]
So @dk-a-dev , now we have to fork the repo which is on your account and push our changes on that only, is that correct?

**Comment by Lomesh21** [comment]
Or we can work on same fork by communicating each other we try to avoid conflicts?

**Comment by dk-a-dev** [comment]
> Or we can work on same fork by communicating each other we try to avoid conflicts? 

Do this instead

**Comment by Lomesh21** [comment]
Ok

**Comment by Lomesh21** [comment]
@dk-a-dev  we make individual pages which are not currently available in project and then make a PR of that and then after the modification of current pages which may cause conflicts!! What's your view??

**Comment by dk-a-dev** [comment]
Create a fork all of u work modifying that and then create a single pr that will be merged...to master...now about hacktoberfest contribution u all have to file pr that will not be merged but reviewed and closed as complete so ur contribution will count

**Comment by SarveshChavan** [comment]
@dk-a-dev we are currently not in the same town and it's hard to communicate. We can do one thing when one of us is working on a page the remaining will work on different issues not on the UI issue so that conflicts won't happen. Currently, @SarveshChavan working on the app flow issue, @Yash-Waghmare is on the app icon, so @Lomesh21 can create a feature issue of the profile page and drawer widget and he will work on it. It is feasible for all of us as a single UI PR will have many files changed so hard to review and hard to understand to whom the changes are requested by you.

**Comment by SarveshChavan** [comment]
I'll work on the App flow today @Yash-Waghmare will work on the App Icon, and @Lomesh21  will work on the profile page and the drawer widget. We will try to complete it today, so it will be easy for you to review and merge them. Let me know shall we go with this?

**Comment by dk-a-dev** [comment]
Yeah just let each other know that u r doin this so u guys won't end up doin same work that's all ...work in whatever way u like

**Comment by dk-a-dev** [comment]
Create as many sub issues u want no worries

**Comment by Yash-Waghmare** [comment]
Hey @dk-a-dev, could you please provide me with a proper png image for the app icon?

**Comment by dk-a-dev** [comment]
@Yash-Waghmare we dont have any app icon:), try designing one

**Comment by Yash-Waghmare** [comment]
> @Yash-Waghmare we dont have any app icon:), try designing one
Okay, no issues

**Comment by SarveshChavan** [comment]
@dk-a-dev, while I was trying to implement the UI, changes I found that we have used a theme (Dark and Light), but due to this there are many places where errors occur, such as when we use theme and define a color for a button we have to use it for each button same thing with icon button. But the icon button which is on top of the repo card is white while the icon button on the app bar is black, thus what I think is using a ternary operator for each color field rather than using theme data. Let me know if will it be OK or not.

**Comment by dk-a-dev** [comment]
Do as u please and it's convenient to u I will see pr suggest changes

**Comment by dk-a-dev** [comment]
@Yash-Waghmare whats the progress with icon

**Comment by Yash-Waghmare** [comment]
> @Yash-Waghmare whats the progress with icon

Working on and will raise the PR.

**Comment by dk-a-dev** [comment]
@Lomesh21 , @SarveshChavan and @Yash-Waghmare 
Amazing work !!
Feel free to take other parts of UI or take a break then continue

**Comment by dk-a-dev** [comment]
I have added more sub-issues ask for assignment

**Comment by dk-a-dev** [comment]
@SarveshChavan are u working on About us page UI

**Comment by dk-a-dev** [comment]
@Yash-Waghmare , @SarveshChavan and @Lomesh21 
Awesome Work guys !! I had an amazing time reviewing ur work and learning a lot from all
I hope u guys also enjoyed contributing to this repo and learnt alot❤
